# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
  # download the artifact drop from the previous job
- task: DownloadBuildArtifacts@0
  inputs:
    artifactName: drop
    downloadPath: $(System.DefaultWorkingDirectory)

  # deploy to Azure Web App staging
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureServiceConOne'
    appName: 'ServiceAdvisorAPI'
    package: $(System.DefaultWorkingDirectory)/**/*.zip
    
- task: PublishBuildArtifacts@1
